/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'localadmin' at '3/9/17 10:10 AM' with Gradle 2.9
 *
 * @author localadmin, @date 3/9/17 10:10 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
